### ISSUE TITLE
Error in UseMethod("select") 

### ISSUE THREAD

**Issue by anallg** [oxford-pharmacoepi/MegaStudy#10]
Hello, I`m executing RunFeasibility with a Spark Databricks conection and I´ve the following error: 

source(here("RunFeasibility.R"))
population after earliestStartDate smaller than sample, ignoring date for sampling
Error in UseMethod("select") : 
  no applicable method for 'select' applied to an object of class "NULL"
In addition: Warning messages:
1: In as.POSIXlt.POSIXct(Sys.time()) :
  unable to identify current timezone 'C':
please set environment variable 'TZ'
2: There were 2 warnings in `dplyr::summarise()`.
The first warning was:
i In argument: `minimum_drug_exposure_days = min(.data$drug_exposure_days, na.rm = T)`.
Caused by warning in `min()`:
! no non-missing arguments to min; returning Inf
i Run dplyr::last_dplyr_warnings() to see the 1 remaining warning. 
3: There were 2 warnings in `dplyr::summarise()`.
The first warning was:
i In argument: `minimum_drug_exposure_days = min(.data$drug_exposure_days, na.rm = T)`.
Caused by warning in `min()`:
! no non-missing arguments to min; returning Inf
i Run dplyr::last_dplyr_warnings() to see the 1 remaining warning. 
4: There were 2 warnings in `dplyr::summarise()`.
The first warning was:
i In argument: `minimum_drug_exposure_quantity = min(.data$quantity, na.rm = T)`.
Caused by warning in `min()`:
! no non-missing arguments to min; returning Inf
i Run dplyr::last_dplyr_warnings() to see the 1 remaining warning. 
5: There were 2 warnings in `dplyr::summarise()`.
The first warning was:
i In argument: `minimum_drug_exposure_quantity = min(.data$quantity, na.rm = T)`.
Caused by warning in `min()`:
! no non-missing arguments to min; returning Inf
i Run dplyr::last_dplyr_warnings() to see the 1 remaining warning. 

Thanks in advance.

**Comment by tiozab** [comment]
@anallg, the select statement occurs in the DrugExposureDiagnostics package in the executeChecks function. 
The code uses the following cdm tables:

cdm$concept_relationship
cdm$concept_ancestor
cdm$concept
cdm$drug_exposure
cdm$drug_strength

Can you make sure that these tables exist in your CDM and that they have all the required columns? Because this error in the select function tells you that it is returning an empty object.

Thanks!

**Comment by anallg** [comment]
@tiozab 

Hello, I´ve checked that all the tables you mention are correct. Its seems correct both in the number of fields and data type. Also, all of then are populated. 
We just ran all the quality scripts, and we haven't encountered any issues. 

Would it be helpful if I send you screenshots of those tables in our system?

**Comment by tiozab** [comment]
@anallg please do not send any screenshots of tables since some of them may contain sensitive information. 
Please change the RunFeasibility.R script in line 100 to verbose == TRUE and run again. 
This way we will know in which part of the executeChecks function the error occurs.

@edward-burn  spark databricks should be supported by DrugExposureDiagnostics, right?

**Comment by anallg** [comment]
@tiozab Hello again, 
 I've been testing and I have it.  I downloaded the source code of DrugExposureDiagnostic to run step by step, and ran it with VERBOSE=TRUE. That's how I realized it was an issue with the version of the library I had installed. 

Anyway, solved!! Thanks for your attention and help.
