### ISSUE TITLE
Problem running DUS.R

### ISSUE THREAD

**Issue by donni29** [oxford-pharmacoepi/MegaStudy#35]
Hello everyone,
We are running the code of "DUS code" and we have obtained the following error during the execution of generateConceptCohortSet (line 124 of DUS.R):

![image](https://github.com/oxford-pharmacoepi/MegaStudy/assets/72864569/204c15d2-6b20-4be6-bf76-8cc6abb6aa8f)

To try to overcome this, we also tried to use an older version of the CDMConnector package (currently 1.3.0) but the same error was generated.
The execution of the other two codes (Feasibility Code and IncidencePrevalence Code)  were successful.

**Comment by tiozab** [comment]
Hi @donni29 which DBMS you are using, and which database?

**Comment by donni29** [comment]
We are using PostgreSQL and the database is the standard CdmV5.4 (nameDB=cdm, schema=public)

**Comment by tiozab** [comment]
Thank you, I meant what is the name of your database @donni29

**Comment by tiozab** [comment]
@catalamarti can you help us? never seen this error before.

**Comment by tiozab** [comment]
@donni29 , the code was update yesterday, so please use the new version. Can you still let us know from which database you come from ? That will help with trouble shooting as well :-)

**Comment by donni29** [comment]
Thanks @tiozab for your help!! We were able to solve the problem by downgrading the version of R and some of the libraries used within the package (therefore no problem related to the type of database used).

**Comment by tiozab** [comment]
@donni29 thanks that is great, yes it is important to use the renv, or individually use the correct version packages, which still change very much. 
Just to double check that you have used the most recent code from this repository, because if not, please run it again (the indications code lists have been updated), sorry for the trouble! The code you had originally was the testing version.
