### ISSUE TITLE
Error in `validateGeneratedCohortSet()`: ! There is overlap between entries in the cohort (4 overlaps detected)

### ISSUE THREAD

**Issue by dandedman** [oxford-pharmacoepi/MegaStudy#41]
@tiozab : I get this error running on the full database. 
I have _redacted_ the actual values in the output but in each of the 4 cases the next_cohort_start_date was 1 day earlier than cohort_end_date.

> condition domain: Adding descendants
> v 116 candidate concepts identified
> Time taken: 1 minutes and 34 seconds
> i Generating 1 cohort
> v Generating cohort (1/1) - covid_19) [8m 14.3s]
> Created a temporary table named #dbplyr_001
> Created a temporary table named #dbplyr_002
> Created a temporary table named #dbplyr_003
> ...
> ...
> Created a temporary table named #dbplyr_039
> Created a temporary table named #dbplyr_040
> Created a temporary table named #dbplyr_041
> Error in `validateGeneratedCohortSet()`:
> ! There is overlap between entries in the cohort, 4 overlaps detected:
> $ cohort_definition_id <int> 1, 1, 1, 1
> $ subject_id <int64> _[output redacted]_ 
> $ cohort_start_date <date> _[output redacted]_ 
> $ cohort_end_date <date> _[output redacted]_ 
> $ next_cohort_start_date <date> _[output redacted]_ 
> 
> Backtrace:
>      x
>   1. +-base::source(...)
>   2. | +-base::withVisible(eval(ei, envir))
>   3. | \-base::eval(ei, envir)
>   4. |   \-base::eval(ei, envir)
>   5. +-base::source(here("DUS.R")) at MegaStudy/DUS Code/CodeToRun_Aurum2309.R:51:1
>   6. | +-base::withVisible(eval(ei, envir))
>   7. | \-base::eval(ei, envir)
>   8. |   \-base::eval(ei, envir)
>   9. \-CDMConnector::generateConceptCohortSet(...) at MegaStudy/DUS Code/DUS.R:121:3
>  10.   \-omopgenerics::newCohortTable(...)
>  11.     \-omopgenerics:::validateGeneratedCohortSet(cohort, soft = .softValidation)

**Comment by tiozab** [comment]
@dandedman, this should be taken care of with a softValidation:

Please replace the following two lines:

line 219:
cdm$inc_pat <- omopgenerics::newCohortTable(cdm[["inc_pat"]], .softValidation = TRUE) 

line 556:
cdm$prev_pat <- omopgenerics::newCohortTable(cdm[["prev_pat"]], .softValidation = TRUE)

**Comment by dandedman** [comment]
@tiozab: I made those changes:

![image](https://github.com/oxford-pharmacoepi/MegaStudy/assets/48352919/ab7b2858-c709-405d-a7d6-1a9c10056f1e)

and

![image](https://github.com/oxford-pharmacoepi/MegaStudy/assets/48352919/64b97002-6fca-4dba-a2aa-f94bc874afa1)

 but still getting the similar error (5 overlaps this time)

> Created a temporary table named #dbplyr_037
> Created a temporary table named #dbplyr_038
> Created a temporary table named #dbplyr_039
> Created a temporary table named #dbplyr_040
> Created a temporary table named #dbplyr_041
> Error in `validateGeneratedCohortSet()`:
> ! There is overlap between entries in the cohort, 5 overlaps detected:
> $ cohort_definition_id <int> 1, 1, 1, 1, 1
> $ subject_id _[output redacted]_
> $ cohort_start_date _[output redacted]_
> $ cohort_end_date _[output redacted]_
> $ next_cohort_start_date _[output redacted]_
> Run `rlang::last_trace()` to see where the error occurred.
> ...
> ...
> Backtrace:
>      x
>   1. +-base::source(...)
>   2. | +-base::withVisible(eval(ei, envir))
>   3. | \-base::eval(ei, envir)
>   4. |   \-base::eval(ei, envir)
>   5. +-base::source(here("DUS.R")) at MegaStudy/DUS Code/CodeToRun_Aurum2309.R:51:1
>   6. | +-base::withVisible(eval(ei, envir))
>   7. | \-base::eval(ei, envir)
>   8. |   \-base::eval(ei, envir)
>   9. \-CDMConnector::generateConceptCohortSet(...) at MegaStudy/DUS Code/DUS.R:121:3
>  10.   \-omopgenerics::newCohortTable(...)
>  11.     \-omopgenerics:::validateGeneratedCohortSet(cohort, soft = .softValidation)

**Comment by tiozab** [comment]
@edward-burn @catalamarti the softValidation should not assess overlapps or was anything changed ? 
https://darwin-eu-dev.github.io/omopgenerics/reference/newCohortTable.html
.softValidation
Whether to perform a soft validation of consistency. If set to FALSE four additional checks will be performed: 1) a check that cohort end date is not before cohort start date, 2) a check that there are no missing values in required columns, 3) a check that cohort duration is all within observation period, and 4) that there are no overlapping cohort entries

**Comment by tiozab** [comment]
@dandedman, where in the log does the error occur? I think the error occurs already earlier than I thought, I don't think your code runs until line 219 but already throws the error at line 121 when generating the indication cohorts, right? It would be helpful to see the log for that instance, because it will tell at which indication in the loop the error is thrown (if it occurs already at line 121)
  cdm <- generateConceptCohortSet(
    cdm,
    conceptSet = ind_list,
    name = ind,  
    limit = "all",
    requiredObservation = c(0, 0),
    end = 1,
    overwrite = TRUE
  )

**Comment by dandedman** [comment]
@tiozab : log attached - yes looks like it failed in same place each time. Log attached

[CPRDAurum2309_log.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/14956757/CPRDAurum2309_log.txt)

**Comment by tiozab** [comment]
ok interesting that helps!
Just delete the smoking cessation from the indication list with a hashtag and run again from line 61
line 101  
#    "smoking_cessation",

**Comment by tiozab** [comment]
@inesreinecke "I get the same error message as @filipmaljkovic , but I think at a different point in the script: this is my error message, when I run: cdm$inc_pat <- omopgenerics::newCohortTable(cdm[["inc_pat"]])

Error in validateGeneratedCohortSet():
! There is overlap between entries in the cohort, 24656 overlaps detected first 5:
$ cohort_definition_id 4, 4, 4, 4, 4
$ subject_id 2749, 3918, 4482, 22871, 23059
$ cohort_start_date 2023-07-12, 2023-07-24, 2020-01-14, 2021-12-08, 2019-01-19
$ cohort_end_date 2023-07-12, 2023-07-24, 2020-01-14, 2021-12-08, 2019-01-19
$ next_cohort_start_date 2023-07-12, 2023-07-24, 2020-01-14, 2021-12-08, 2019-01-19

my complete log file is here:
[UM DRESDEN_log.txt](https://github.com/oxford-pharmacoepi/MegaStudy/files/15385232/UM.DRESDEN_log.txt)"

Thanks, the above softValidation should take care of it:
comment from April 11

line 219:
cdm$inc_pat <- omopgenerics::newCohortTable(cdm[["inc_pat"]], .softValidation = TRUE)

line 556:
cdm$prev_pat <- omopgenerics::newCohortTable(cdm[["prev_pat"]], .softValidation = TRUE)

**Comment by tiozab** [comment]
@mikaelhogerman reports this issue

So Igot error #41 and I tried changing lines 219 and 556 like suggested in git (attached log_infection for this).
CPRDAurum's log failed at somking, but our failed at infection. @tiozab comments here: this was the log that stopped Aug 30.

I applied the same logic and commented that but then I got error in attachements.
@tiozab this is the log that stopped Sep 10 

[University of Turku (PCASF)_log.txt](https://github.com/user-attachments/files/16960838/University.of.Turku.PCASF._log.txt)

"xxx observations outside observation period"
I didn't find this error from git.
![Näyttökuva (31)](https://github.com/user-attachments/assets/51de5944-5e83-432d-add9-79baf4315e99)

The same error occurs with both normal DUS.R and DUS_1point4.R
Any ideas about this error?

@tiozab comments: 
the first run Aug 30 does not create an error with COVID (because the covid occurs before before you log stops for infection).
then your run on Sep 9 stops at the error depicted in the picture (at covid cohort generation with the error that there are observations outside the observation period.
That said, can you run the script until (excluding) "name_indication <- c("neutropenia"," ... with whichever settings / script you were using on Aug 30 (to succesfully get the covid cohort) and the continue (while keeping all the objects in your environment) with the R script DUS_1point4.R from "name_indication <- c("neutropenia"," ... commenting out infection since that gave an error .... and try to continue this way?
