### ISSUE TITLE
IncidencePrevalence Export Issue

### ISSUE THREAD

**Issue by JordiRodeiroSJD** [oxford-pharmacoepi/MegaStudy#70]
Hi,

I am encountering an error in the Incidence-Prevalence section.

As noted in the image of the error trace, a function called in the code cannot be found.

![IncidencePrevalence error](https://github.com/oxford-pharmacoepi/MegaStudy/assets/174800149/2e1de9ad-e01c-4cde-99b9-9b4b0377e2d6)

Could you please provide me with assistance?

Thanks,
Jordi Rodeiro

**Comment by tiozab** [comment]
@JordiRodeiroSJD can you let me know which version of Incidence Prevalence you are using, and your database management system? Thank you. 

@edward-burn any idea what is going on that all of a sudden functions cannot be found? same as the other issue https://github.com/oxford-pharmacoepi/MegaStudy/issues/68 in Codelistgenerator?

**Comment by JordiRodeiroSJD** [comment]
I am using a SQLServer Database and the Incidence Prevalence version is 0.7.4.

**Comment by tiozab** [comment]
Thanks @JordiRodeiroSJD please use the renv.lock file and make sure it works properly :-)

**Comment by JordiRodeiroSJD** [comment]
When trying to use the renv.lock, an error pops up.

Error: Error installing package 'curl':
Error in download.file(url, basename(url), quiet = TRUE) :
  cannot open URL 'https://github.com/r-windows/bundles/releases/download/curl-8.3.0/curl-8.3.0-ucrt-x86_64.tar.xz'

I understand that is not from your code, but it unables me from using the renv.lock provided.

**Comment by tiozab** [comment]
@JordiRodeiroSJD just found this on stackoverflow. 
https://stackoverflow.com/questions/35931342/r-cannot-access-urls-for-package-installation

try running this command before the renv activation?
options(repos="https://CRAN.R-project.org")
however, there is one package that comes from OHDSI (circeR 1.3.1)

otherwise please install the correct versions of the following packages separately:

 "Package": "PatientProfiles",
      "Version": "0.4.0",

     "Package": "CDMConnector",
      "Version": "1.2.1",

    "Package": "IncidencePrevalence",
      "Version": "0.6.0",

  "Package": "DrugUtilisation",
      "Version": "0.4.1",

      "Package": "dbplyr",
      "Version": "2.4.0",

   "Package": "CodelistGenerator",
      "Version": "2.1.1",

      "Package": "MASS",
      "Version": "7.3-60",

      "Package": "curl",
      "Version": "5.1.0",

from ohdsi:
   "CirceR": {
      "Package": "CirceR",
      "Version": "1.3.1",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "CirceR",
      "RemoteUsername": "ohdsi",

Until here are the relevant ones.

and you can look up the other versions for these packages, however I dont think their version matters:
library("devtools")
library("odbc")
library("RPostgres")
library("DBI")
library("dplyr")

library("here")
library("log4r")
library("zip")

library("tidyr")
library("ggplot2")
library("Capr")
library("testthat")

**Comment by JordiRodeiroSJD** [comment]
I managed to use the renv.lock by deleting some of the included packages and it works. Thanks!

**Comment by JordiRodeiroSJD** [comment]
I deleted packages V8, curl, gert, httpuv, openssl, and rJava from the renv.lock, and I used the versions that I had already installed locally without the renv. The versions I used are 4.3.3 (V8), 5.1.0 (curl), 2.0.1 (gert), 1.6.15 (httpuv), 2.1.1 (openssl), and 1.0.11 (rJava).
